name: country_utils
description: "A Flutter package providing easy access to country names, ISO codes and more. Streamline your development with functions for country data retrieval and manipulation."
version: 0.2.0
homepage: https://github.com/RoadTripMoustache/country_utils

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/i18n/
