name: service_example
description: "A country utils example with services"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.7.0-102.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  country_utils:
    path: "./../../"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
